<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="AttributedFMs" nsURI="http://caosd.lcc.uma.es/AttributedFMs"
    nsPrefix="AttributedFMs">
  <eClassifiers xsi:type="ecore:EClass" name="AttributedFM" eSuperTypes="../BasicFMmetamodel.ecore#//FeatureModel"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute"/>
</ecore:EPackage>
