<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="DataTypes" nsURI="http://caosd.lcc.uma.es/DataTypes" nsPrefix="DataTypes">
  <eClassifiers xsi:type="ecore:EClass" name="DataType" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="PrimitiveTypeEnum">
    <eLiterals name="Boolean"/>
    <eLiterals name="Natural" value="1"/>
    <eLiterals name="Integer" value="2"/>
    <eLiterals name="Real" value="3"/>
    <eLiterals name="String" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" eSuperTypes="#//DataType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//PrimitiveTypeEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedFeature" eSuperTypes="../BasicFMmetamodel.ecore#//Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//Value" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectType" eSuperTypes="#//DataType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//Object"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Object" instanceTypeName="Object"/>
</ecore:EPackage>
